# Generated by Django 3.2.16 on 2022-11-01 02:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите категорию', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_add', models.DateField(blank=True, null=True)),
                ('name', models.CharField(default='Отвали', max_length=200, verbose_name='Название')),
                ('summary', models.TextField(help_text='Описание', max_length=1000)),
                ('comment', models.TextField(blank=True, help_text='Комментарий', max_length=1000)),
                ('img', models.ImageField(blank=True, max_length=200, null=True, upload_to=portal.utilities.get_timestamp_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('status', models.CharField(blank=True, choices=[('n', 'Новая'), ('a', 'Принято в работу'), ('c', 'Выполнено')], default='n', max_length=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Выбор категории', on_delete=django.db.models.deletion.CASCADE, to='portal.category')),
            ],
            options={
                'ordering': ['status'],
                'permissions': (('can_mark_returned', 'Установите статус заказа'),),
            },
        ),
    ]
