# Generated by Django 3.2.16 on 2022-11-01 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='comment',
        ),
    ]
