# Generated by Django 3.2.16 on 2022-10-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='user_agreement',
        ),
    ]
