# Generated by Django 3.2.16 on 2022-10-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_advuser_user_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='user_agreement',
            field=models.BooleanField(db_index=True, default=False, help_text='Прочел и ознакомлен с <a href="http://www.sfmolga.ru/agreement.pdf">Пользовательским соглашением</a>'),
        ),
    ]
